### ISSUE TITLE
[WICHTIG] Strings statt Lambda Ausdrücke für compute/search/inverse Field Properties verwenden! Für andere Field Properties Lambdas oder direkte Werte benutzen.

### ISSUE THREAD

**Issue by Kleesi** [SNeuhausen/training_management#12]
Statt eines Lambda Ausdrucks:

```
mein_feld = fields.Char(compute=lambda self: self._compute__mein_feld())
```

Einen String verwenden: (auch wenn das natürlich wieder die Fehleranfälligkeit erhöht)

```
mein_feld = fields.Char(compute="_compute__mein_feld")
```

Wobei die compute Methode so definiert ist:

```
@api.depends('feld1', 'feld2')
def _compute__mein_feld(self):
...
```

Warum?
Weil ansonsten die `depends` Angaben schlichtweg ignoriert werden. Weiterer Vorteil: wenn man die compute Methode überschreibt und der überschriebenen Methode neue Felder per `depends` hinzugefügt, dann werden diese mit den bisher definierten Feldangaben vereinigt.

Hintergrud:
Die Decorator Funktion `depends` hängt ein Attribut namens `_depends` an die zu dekorierende Methode an, wobei der Wert dieses Attributs aus einem Tupel der Argumente der `decorate`Funktion besteht. Für obiges Beispiel lautet der Wert für das Attribut `_depends` der Methode `_compute__mein_feld`: `('feld1', 'feld2')`. Der Wert dieses Attributs wird beim Setup des computed Fields `mein_feld` ausgewertet und anhand dessen die Trigger der Felder berechnet, die letztlich für das Anstoßen der compute Methode von `mein_feld` mit verantwortlich sind (hier: `feld1` und `feld2`)

Beim Trigger Setup wird der direkte Wert der `compute` Eigenschaft verwendet. Wenn man hier statt eines Strings ein Lambda Ausdruck wählt, dann versucht die Setup Funktion das `_depends` Attribut des Lambda Ausdrucks zu lesen und das ist natürlich immer leer, denn es wird ja nicht der Lambda Ausdruck dekoriert, sondern die compute Methode selbst. Bei Verwendung eines Strings für compute sucht die Setup Funktion die angegebene Methode aus der Klasse heraus und ermittelt deren `_depends` Attribut. Hier schaut die setup Funktion nun an der richtigen Stelle.

**Comment by SNeuhausen** [comment]
ok
