### ISSUE TITLE
[WICHTIG] Statusbar Widget Bug in Odoo 9.0c

### ISSUE THREAD

**Issue by Kleesi** [SNeuhausen/training_management#21]
Das Statusbar Widget verhält sich fehlerhaft, wenn es in einem Dialogfenster verwendet wird, das sich gerade im Ansichtsmodus befindet. Man kann zwar per Mausklick den Status der Statusbar ändern, aber dieser Status wird nicht in der Datenbank persistiert.

Ursache: wenn ein Formular in einem Dialogfenster dargestellt wird, dann gehört der per Formular dargestellte Datensatz zum Datensatz des übergeordneten Formulars. Nur wenn der übergeordnete Datensatz gespeichert wird, werden auch die Daten des untergeordneten Datensatzes gespeichert.  Wird aber auch der übergeordnete Datensatz im Ansichtsmodus angezeigt, ist das Speichern gar nicht möglich. Folglich gehen die Daten in jedem Fall verloren.
Die Änderung des Statusbar Widgets im Dialogfenster führt lediglich zu einem onchange, statt zu einem write Methodenaufruf! Deshalb werden die Daten auch erst dann gespeichert, wenn der übergeordnete Datensatz per write in die Datenbank persistiert wird.

**Comment by SNeuhausen** [comment]
OK - auch keine Lösung gefunden. Gleiches gilt für Action Button
