### ISSUE TITLE
[Wichtig] Dependencies für computed Fields _exakt_ angeben!

### ISSUE THREAD

**Issue by Kleesi** [SNeuhausen/training_management#22]
Hängt der Wert eines computed Fields von einem Feldwert eines relationalen Feldes ab, dann reicht es in der Regel nicht aus, nur den Namen des relationalen Feldes als Dependency anzugeben.

Beispiel: 
Partner <--(one)---------(many)-- Education Plan
Angenommen das Feld `Partner.status` hängt von `EducationPlan.status` ab, dann muss die Dependency Angabe so lauten:

```
# models/partner.py
@depends("education_plan_id.status")
def _compute__status(self):
    ...
```

Diese Dependency Angabe besagt folgendes:
1. Berechne `status` neu, wenn sich die Datenbank ID `education_plan_id.id` ändert.
2. Berechne `status`neu, wenn sich der Wert des Feldes `status` im Datensatz `education_plan_id` ändert.

Es reicht in diesem Fall also nicht aus, einfach nur `education_plan_id` als Dependency anzugeben.

**Comment by SNeuhausen** [comment]
OK
