### ISSUE TITLE
Gantt View aktualisiert sich nicht, nachdem sie einmal gerendert wurde

### ISSUE THREAD

**Issue by Kleesi** [SNeuhausen/training_management#25]
Wurde der Inhalt für die Gantt View bereits gerendert, dann wird die Gantt View trotz Neuberechnung des Gantt Contents nicht neu gerendert. Man muss erst einen anderen Menüpunkt wählen und dann in die Kurse zurückspringen.

**Comment by SNeuhausen** [comment]
fixed
