### ISSUE TITLE
[WICHTIG] Unicode Strings verwenden wenn nicht ASCII Zeichen verwendet werden

### ISSUE THREAD

**Issue by Kleesi** [SNeuhausen/training_management#26]
Um Konvertierungsprobleme zwischen normalen Byte Strings und Unicode Strings zu vermeiden, bitte Unicode Strings verwenden, sofern man davon ausgehen kann, dass die Strings auch Umlaute bzw. Nicht Ascii Zeichen enthalten.

Beispiel: Statt `s = "Thüringen` besser `s = u"Thüringen"` schreiben.

**Comment by SNeuhausen** [comment]
OK
