### ISSUE TITLE
Überarbeitung Teilnehmer und Trainer Modell

### ISSUE THREAD

**Issue by SNeuhausen** [SNeuhausen/training_management#3]
Erweiterung von res.partner
Checkboxen für Kategorien:
- Teilnehmer
- Trainer
- Kostenträger
Views selektieren über Domain

**Comment by Kleesi** [comment]
Aktueller Stand befindet sich im Moment noch im Branch "tm_partner", da noch nicht alles funktioniert wie es soll =). Server Action für das Kopieren des Status in den Teilnehmer und das Demarkieren aller anderen Bildungswege für diesen Teilnehmer ist in neuer API Form implementiert. Scheint auch problemlos zu funktionieren.

**Comment by Kleesi** [comment]
Alles implementiert. Muss aber noch ausgiebig getestet werden.
